### ISSUE TITLE
Nectar/waggle should try to call registrar a few times before giving up

### ISSUE THREAD

**Issue by EmiM** [ZbayApp/nectar#10]

**Comment by holmesworcester** [comment]
For this I think it should actually retry forever, on some cycle. This way, when both the admin user (running the registrar) and the invited user are online at the same time, a connection will be made and registration can take place.

**Comment by holmesworcester** [comment]
Nectar / waggle would communicate this "registrar offline, retrying" state to the frontend so that the user could be notified
